// This file was generated by counterfeiter
package opspec

import (
	"sync"

	"github.com/opspec-io/sdk-golang/models"
)

type fakeCreateCollectionUseCase struct {
	ExecuteStub        func(req models.CreateCollectionReq) (err error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		req models.CreateCollectionReq
	}
	executeReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeCreateCollectionUseCase) Execute(req models.CreateCollectionReq) (err error) {
	fake.executeMutex.Lock()
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		req models.CreateCollectionReq
	}{req})
	fake.recordInvocation("Execute", []interface{}{req})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(req)
	} else {
		return fake.executeReturns.result1
	}
}

func (fake *fakeCreateCollectionUseCase) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *fakeCreateCollectionUseCase) ExecuteArgsForCall(i int) models.CreateCollectionReq {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].req
}

func (fake *fakeCreateCollectionUseCase) ExecuteReturns(result1 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 error
	}{result1}
}

func (fake *fakeCreateCollectionUseCase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.invocations
}

func (fake *fakeCreateCollectionUseCase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
