// This file was generated by counterfeiter
package osfilesys

import "sync"

type FakeSaveDevOpFileUcExecuter struct {
  ExecuteStub        func(devOpName string, data []byte) (err error)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    devOpName string
    data      []byte
  }
  executeReturns     struct {
                       result1 error
                     }
}

func (fake *FakeSaveDevOpFileUcExecuter) Execute(devOpName string, data []byte) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    devOpName string
    data      []byte
  }{devOpName, data})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    return fake.ExecuteStub(devOpName, data)
  } else {
    return fake.executeReturns.result1
  }
}

func (fake *FakeSaveDevOpFileUcExecuter) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *FakeSaveDevOpFileUcExecuter) ExecuteArgsForCall(i int) (string, []byte) {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].devOpName, fake.executeArgsForCall[i].data
}

func (fake *FakeSaveDevOpFileUcExecuter) ExecuteReturns(result1 error) {
  fake.ExecuteStub = nil
  fake.executeReturns = struct {
    result1 error
  }{result1}
}
