description: deploys website to github pages
name: deploy
inputs:
  github:
    object:
      constraints:
        properties:
          accessToken:
            minLength: 1
            type: string
            writeOnly: true
          username:
            minLength: 1
            type: string
        required: [accessToken, username]
      description: configuration required to interact w/ github
  HOME:
    dir:
      description: Home directory of caller; used to access go modules
run:
  serial:
    - op:
        ref: $(../init)
        inputs:
          HOME:
    - container:
        cmd: [/cmd.sh]
        dirs:
          /src: $(../../..)
        envVars:
          GIT_USER: $(github.username)
          GITHUB_ACCESS_TOKEN: $(github.accessToken)
        files:
          /cmd.sh:
          /root/.netrc: |
            machine github.com
            login $(github.username)
            password $(github.accessToken)
        image: { ref: 'node:20' }
        workDir: /src/website
