// This file was generated by counterfeiter
package pubsub

import (
	"sync"

	"github.com/opspec-io/sdk-golang/model"
)

type Fake struct {
	PublishStub        func(event *model.Event)
	publishMutex       sync.RWMutex
	publishArgsForCall []struct {
		event *model.Event
	}
	SubscribeStub        func(filter *model.EventFilter, eventChannel chan *model.Event)
	subscribeMutex       sync.RWMutex
	subscribeArgsForCall []struct {
		filter       *model.EventFilter
		eventChannel chan *model.Event
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Fake) Publish(event *model.Event) {
	fake.publishMutex.Lock()
	fake.publishArgsForCall = append(fake.publishArgsForCall, struct {
		event *model.Event
	}{event})
	fake.recordInvocation("Publish", []interface{}{event})
	fake.publishMutex.Unlock()
	if fake.PublishStub != nil {
		fake.PublishStub(event)
	}
}

func (fake *Fake) PublishCallCount() int {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return len(fake.publishArgsForCall)
}

func (fake *Fake) PublishArgsForCall(i int) *model.Event {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return fake.publishArgsForCall[i].event
}

func (fake *Fake) Subscribe(filter *model.EventFilter, eventChannel chan *model.Event) {
	fake.subscribeMutex.Lock()
	fake.subscribeArgsForCall = append(fake.subscribeArgsForCall, struct {
		filter       *model.EventFilter
		eventChannel chan *model.Event
	}{filter, eventChannel})
	fake.recordInvocation("Subscribe", []interface{}{filter, eventChannel})
	fake.subscribeMutex.Unlock()
	if fake.SubscribeStub != nil {
		fake.SubscribeStub(filter, eventChannel)
	}
}

func (fake *Fake) SubscribeCallCount() int {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return len(fake.subscribeArgsForCall)
}

func (fake *Fake) SubscribeArgsForCall(i int) (*model.EventFilter, chan *model.Event) {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return fake.subscribeArgsForCall[i].filter, fake.subscribeArgsForCall[i].eventChannel
}

func (fake *Fake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return fake.invocations
}

func (fake *Fake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ PubSub = new(Fake)
