// Code generated by counterfeiter. DO NOT EDIT.
package containerprovider

import (
	"io"
	"sync"

	"github.com/opctl/opctl/util/pubsub"
	"github.com/opspec-io/sdk-golang/model"
)

type Fake struct {
	DeleteContainerIfExistsStub        func(containerId string) error
	deleteContainerIfExistsMutex       sync.RWMutex
	deleteContainerIfExistsArgsForCall []struct {
		containerId string
	}
	deleteContainerIfExistsReturns struct {
		result1 error
	}
	deleteContainerIfExistsReturnsOnCall map[int]struct {
		result1 error
	}
	NetworkContainerStub        func(networkId string, containerId string, containerAlias string) error
	networkContainerMutex       sync.RWMutex
	networkContainerArgsForCall []struct {
		networkId      string
		containerId    string
		containerAlias string
	}
	networkContainerReturns struct {
		result1 error
	}
	networkContainerReturnsOnCall map[int]struct {
		result1 error
	}
	RunContainerStub        func(req *model.DCGContainerCall, eventPublisher pubsub.EventPublisher, stdout io.WriteCloser, stderr io.WriteCloser) (*int64, error)
	runContainerMutex       sync.RWMutex
	runContainerArgsForCall []struct {
		req            *model.DCGContainerCall
		eventPublisher pubsub.EventPublisher
		stdout         io.WriteCloser
		stderr         io.WriteCloser
	}
	runContainerReturns struct {
		result1 *int64
		result2 error
	}
	runContainerReturnsOnCall map[int]struct {
		result1 *int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Fake) DeleteContainerIfExists(containerId string) error {
	fake.deleteContainerIfExistsMutex.Lock()
	ret, specificReturn := fake.deleteContainerIfExistsReturnsOnCall[len(fake.deleteContainerIfExistsArgsForCall)]
	fake.deleteContainerIfExistsArgsForCall = append(fake.deleteContainerIfExistsArgsForCall, struct {
		containerId string
	}{containerId})
	fake.recordInvocation("DeleteContainerIfExists", []interface{}{containerId})
	fake.deleteContainerIfExistsMutex.Unlock()
	if fake.DeleteContainerIfExistsStub != nil {
		return fake.DeleteContainerIfExistsStub(containerId)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteContainerIfExistsReturns.result1
}

func (fake *Fake) DeleteContainerIfExistsCallCount() int {
	fake.deleteContainerIfExistsMutex.RLock()
	defer fake.deleteContainerIfExistsMutex.RUnlock()
	return len(fake.deleteContainerIfExistsArgsForCall)
}

func (fake *Fake) DeleteContainerIfExistsArgsForCall(i int) string {
	fake.deleteContainerIfExistsMutex.RLock()
	defer fake.deleteContainerIfExistsMutex.RUnlock()
	return fake.deleteContainerIfExistsArgsForCall[i].containerId
}

func (fake *Fake) DeleteContainerIfExistsReturns(result1 error) {
	fake.DeleteContainerIfExistsStub = nil
	fake.deleteContainerIfExistsReturns = struct {
		result1 error
	}{result1}
}

func (fake *Fake) DeleteContainerIfExistsReturnsOnCall(i int, result1 error) {
	fake.DeleteContainerIfExistsStub = nil
	if fake.deleteContainerIfExistsReturnsOnCall == nil {
		fake.deleteContainerIfExistsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteContainerIfExistsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Fake) NetworkContainer(networkId string, containerId string, containerAlias string) error {
	fake.networkContainerMutex.Lock()
	ret, specificReturn := fake.networkContainerReturnsOnCall[len(fake.networkContainerArgsForCall)]
	fake.networkContainerArgsForCall = append(fake.networkContainerArgsForCall, struct {
		networkId      string
		containerId    string
		containerAlias string
	}{networkId, containerId, containerAlias})
	fake.recordInvocation("NetworkContainer", []interface{}{networkId, containerId, containerAlias})
	fake.networkContainerMutex.Unlock()
	if fake.NetworkContainerStub != nil {
		return fake.NetworkContainerStub(networkId, containerId, containerAlias)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.networkContainerReturns.result1
}

func (fake *Fake) NetworkContainerCallCount() int {
	fake.networkContainerMutex.RLock()
	defer fake.networkContainerMutex.RUnlock()
	return len(fake.networkContainerArgsForCall)
}

func (fake *Fake) NetworkContainerArgsForCall(i int) (string, string, string) {
	fake.networkContainerMutex.RLock()
	defer fake.networkContainerMutex.RUnlock()
	return fake.networkContainerArgsForCall[i].networkId, fake.networkContainerArgsForCall[i].containerId, fake.networkContainerArgsForCall[i].containerAlias
}

func (fake *Fake) NetworkContainerReturns(result1 error) {
	fake.NetworkContainerStub = nil
	fake.networkContainerReturns = struct {
		result1 error
	}{result1}
}

func (fake *Fake) NetworkContainerReturnsOnCall(i int, result1 error) {
	fake.NetworkContainerStub = nil
	if fake.networkContainerReturnsOnCall == nil {
		fake.networkContainerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.networkContainerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Fake) RunContainer(req *model.DCGContainerCall, eventPublisher pubsub.EventPublisher, stdout io.WriteCloser, stderr io.WriteCloser) (*int64, error) {
	fake.runContainerMutex.Lock()
	ret, specificReturn := fake.runContainerReturnsOnCall[len(fake.runContainerArgsForCall)]
	fake.runContainerArgsForCall = append(fake.runContainerArgsForCall, struct {
		req            *model.DCGContainerCall
		eventPublisher pubsub.EventPublisher
		stdout         io.WriteCloser
		stderr         io.WriteCloser
	}{req, eventPublisher, stdout, stderr})
	fake.recordInvocation("RunContainer", []interface{}{req, eventPublisher, stdout, stderr})
	fake.runContainerMutex.Unlock()
	if fake.RunContainerStub != nil {
		return fake.RunContainerStub(req, eventPublisher, stdout, stderr)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.runContainerReturns.result1, fake.runContainerReturns.result2
}

func (fake *Fake) RunContainerCallCount() int {
	fake.runContainerMutex.RLock()
	defer fake.runContainerMutex.RUnlock()
	return len(fake.runContainerArgsForCall)
}

func (fake *Fake) RunContainerArgsForCall(i int) (*model.DCGContainerCall, pubsub.EventPublisher, io.WriteCloser, io.WriteCloser) {
	fake.runContainerMutex.RLock()
	defer fake.runContainerMutex.RUnlock()
	return fake.runContainerArgsForCall[i].req, fake.runContainerArgsForCall[i].eventPublisher, fake.runContainerArgsForCall[i].stdout, fake.runContainerArgsForCall[i].stderr
}

func (fake *Fake) RunContainerReturns(result1 *int64, result2 error) {
	fake.RunContainerStub = nil
	fake.runContainerReturns = struct {
		result1 *int64
		result2 error
	}{result1, result2}
}

func (fake *Fake) RunContainerReturnsOnCall(i int, result1 *int64, result2 error) {
	fake.RunContainerStub = nil
	if fake.runContainerReturnsOnCall == nil {
		fake.runContainerReturnsOnCall = make(map[int]struct {
			result1 *int64
			result2 error
		})
	}
	fake.runContainerReturnsOnCall[i] = struct {
		result1 *int64
		result2 error
	}{result1, result2}
}

func (fake *Fake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteContainerIfExistsMutex.RLock()
	defer fake.deleteContainerIfExistsMutex.RUnlock()
	fake.networkContainerMutex.RLock()
	defer fake.networkContainerMutex.RUnlock()
	fake.runContainerMutex.RLock()
	defer fake.runContainerMutex.RUnlock()
	return fake.invocations
}

func (fake *Fake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ContainerProvider = new(Fake)
