// This file was generated by counterfeiter
package core

import (
	"sync"

	"github.com/opspec-io/sdk-golang/pkg/model"
)

type fakeOpCaller struct {
	CallStub        func(args map[string]*model.Data, opId string, pkgRef string, rootOpId string) (outputs map[string]*model.Data, err error)
	callMutex       sync.RWMutex
	callArgsForCall []struct {
		args     map[string]*model.Data
		opId     string
		pkgRef   string
		rootOpId string
	}
	callReturns struct {
		result1 map[string]*model.Data
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeOpCaller) Call(args map[string]*model.Data, opId string, pkgRef string, rootOpId string) (outputs map[string]*model.Data, err error) {
	fake.callMutex.Lock()
	fake.callArgsForCall = append(fake.callArgsForCall, struct {
		args     map[string]*model.Data
		opId     string
		pkgRef   string
		rootOpId string
	}{args, opId, pkgRef, rootOpId})
	fake.recordInvocation("Call", []interface{}{args, opId, pkgRef, rootOpId})
	fake.callMutex.Unlock()
	if fake.CallStub != nil {
		return fake.CallStub(args, opId, pkgRef, rootOpId)
	} else {
		return fake.callReturns.result1, fake.callReturns.result2
	}
}

func (fake *fakeOpCaller) CallCallCount() int {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return len(fake.callArgsForCall)
}

func (fake *fakeOpCaller) CallArgsForCall(i int) (map[string]*model.Data, string, string, string) {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return fake.callArgsForCall[i].args, fake.callArgsForCall[i].opId, fake.callArgsForCall[i].pkgRef, fake.callArgsForCall[i].rootOpId
}

func (fake *fakeOpCaller) CallReturns(result1 map[string]*model.Data, result2 error) {
	fake.CallStub = nil
	fake.callReturns = struct {
		result1 map[string]*model.Data
		result2 error
	}{result1, result2}
}

func (fake *fakeOpCaller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return fake.invocations
}

func (fake *fakeOpCaller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
