// Code generated by counterfeiter. DO NOT EDIT.
package string

import (
	"sync"

	"github.com/opspec-io/sdk-golang/model"
)

type fakeInterpreter struct {
	InterpretStub        func(scope map[string]*model.Value, expression string) (string, error)
	interpretMutex       sync.RWMutex
	interpretArgsForCall []struct {
		scope      map[string]*model.Value
		expression string
	}
	interpretReturns struct {
		result1 string
		result2 error
	}
	interpretReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeInterpreter) Interpret(scope map[string]*model.Value, expression string) (string, error) {
	fake.interpretMutex.Lock()
	ret, specificReturn := fake.interpretReturnsOnCall[len(fake.interpretArgsForCall)]
	fake.interpretArgsForCall = append(fake.interpretArgsForCall, struct {
		scope      map[string]*model.Value
		expression string
	}{scope, expression})
	fake.recordInvocation("Interpret", []interface{}{scope, expression})
	fake.interpretMutex.Unlock()
	if fake.InterpretStub != nil {
		return fake.InterpretStub(scope, expression)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.interpretReturns.result1, fake.interpretReturns.result2
}

func (fake *fakeInterpreter) InterpretCallCount() int {
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	return len(fake.interpretArgsForCall)
}

func (fake *fakeInterpreter) InterpretArgsForCall(i int) (map[string]*model.Value, string) {
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	return fake.interpretArgsForCall[i].scope, fake.interpretArgsForCall[i].expression
}

func (fake *fakeInterpreter) InterpretReturns(result1 string, result2 error) {
	fake.InterpretStub = nil
	fake.interpretReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *fakeInterpreter) InterpretReturnsOnCall(i int, result1 string, result2 error) {
	fake.InterpretStub = nil
	if fake.interpretReturnsOnCall == nil {
		fake.interpretReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.interpretReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *fakeInterpreter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *fakeInterpreter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ interpreter = new(fakeInterpreter)
