// Code generated by counterfeiter. DO NOT EDIT.
package string

import (
	"sync"

	"github.com/opspec-io/sdk-golang/model"
)

type Fake struct {
	InterpretStub        func(scope map[string]*model.Value, expression string) (string, error)
	interpretMutex       sync.RWMutex
	interpretArgsForCall []struct {
		scope      map[string]*model.Value
		expression string
	}
	interpretReturns struct {
		result1 string
		result2 error
	}
	interpretReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ValidateStub        func(value *string, constraints *model.StringConstraints) (errors []error)
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		value       *string
		constraints *model.StringConstraints
	}
	validateReturns struct {
		result1 []error
	}
	validateReturnsOnCall map[int]struct {
		result1 []error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Fake) Interpret(scope map[string]*model.Value, expression string) (string, error) {
	fake.interpretMutex.Lock()
	ret, specificReturn := fake.interpretReturnsOnCall[len(fake.interpretArgsForCall)]
	fake.interpretArgsForCall = append(fake.interpretArgsForCall, struct {
		scope      map[string]*model.Value
		expression string
	}{scope, expression})
	fake.recordInvocation("Interpret", []interface{}{scope, expression})
	fake.interpretMutex.Unlock()
	if fake.InterpretStub != nil {
		return fake.InterpretStub(scope, expression)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.interpretReturns.result1, fake.interpretReturns.result2
}

func (fake *Fake) InterpretCallCount() int {
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	return len(fake.interpretArgsForCall)
}

func (fake *Fake) InterpretArgsForCall(i int) (map[string]*model.Value, string) {
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	return fake.interpretArgsForCall[i].scope, fake.interpretArgsForCall[i].expression
}

func (fake *Fake) InterpretReturns(result1 string, result2 error) {
	fake.InterpretStub = nil
	fake.interpretReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Fake) InterpretReturnsOnCall(i int, result1 string, result2 error) {
	fake.InterpretStub = nil
	if fake.interpretReturnsOnCall == nil {
		fake.interpretReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.interpretReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Fake) Validate(value *string, constraints *model.StringConstraints) (errors []error) {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		value       *string
		constraints *model.StringConstraints
	}{value, constraints})
	fake.recordInvocation("Validate", []interface{}{value, constraints})
	fake.validateMutex.Unlock()
	if fake.ValidateStub != nil {
		return fake.ValidateStub(value, constraints)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.validateReturns.result1
}

func (fake *Fake) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *Fake) ValidateArgsForCall(i int) (*string, *model.StringConstraints) {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return fake.validateArgsForCall[i].value, fake.validateArgsForCall[i].constraints
}

func (fake *Fake) ValidateReturns(result1 []error) {
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 []error
	}{result1}
}

func (fake *Fake) ValidateReturnsOnCall(i int, result1 []error) {
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 []error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 []error
	}{result1}
}

func (fake *Fake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.interpretMutex.RLock()
	defer fake.interpretMutex.RUnlock()
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Fake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ String = new(Fake)
