// Code generated by counterfeiter. DO NOT EDIT.
package docker

import (
	"context"
	"sync"

	"github.com/opctl/sdk-golang/model"
	"github.com/opctl/sdk-golang/util/pubsub"
)

type fakeImagePuller struct {
	PullStub        func(ctx context.Context, dcgContainerImage *model.DCGContainerCallImage, containerID string, rootOpID string, eventPublisher pubsub.EventPublisher) error
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		ctx               context.Context
		dcgContainerImage *model.DCGContainerCallImage
		containerID       string
		rootOpID          string
		eventPublisher    pubsub.EventPublisher
	}
	pullReturns struct {
		result1 error
	}
	pullReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeImagePuller) Pull(ctx context.Context, dcgContainerImage *model.DCGContainerCallImage, containerID string, rootOpID string, eventPublisher pubsub.EventPublisher) error {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		ctx               context.Context
		dcgContainerImage *model.DCGContainerCallImage
		containerID       string
		rootOpID          string
		eventPublisher    pubsub.EventPublisher
	}{ctx, dcgContainerImage, containerID, rootOpID, eventPublisher})
	fake.recordInvocation("Pull", []interface{}{ctx, dcgContainerImage, containerID, rootOpID, eventPublisher})
	fake.pullMutex.Unlock()
	if fake.PullStub != nil {
		return fake.PullStub(ctx, dcgContainerImage, containerID, rootOpID, eventPublisher)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.pullReturns.result1
}

func (fake *fakeImagePuller) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *fakeImagePuller) PullArgsForCall(i int) (context.Context, *model.DCGContainerCallImage, string, string, pubsub.EventPublisher) {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return fake.pullArgsForCall[i].ctx, fake.pullArgsForCall[i].dcgContainerImage, fake.pullArgsForCall[i].containerID, fake.pullArgsForCall[i].rootOpID, fake.pullArgsForCall[i].eventPublisher
}

func (fake *fakeImagePuller) PullReturns(result1 error) {
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 error
	}{result1}
}

func (fake *fakeImagePuller) PullReturnsOnCall(i int, result1 error) {
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *fakeImagePuller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *fakeImagePuller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
