// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeSetDescriptionOfPipelineUseCase struct {
  ExecuteStub        func(req models.SetDescriptionOfPipelineReq)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    req models.SetDescriptionOfPipelineReq
  }
}

func (fake *fakeSetDescriptionOfPipelineUseCase) Execute(req models.SetDescriptionOfPipelineReq) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    req models.SetDescriptionOfPipelineReq
  }{req})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    fake.ExecuteStub(req)
  }

  return
}

func (fake *fakeSetDescriptionOfPipelineUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeSetDescriptionOfPipelineUseCase) ExecuteArgsForCall(i int) models.SetDescriptionOfPipelineReq {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].req
}
