// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeAddSubOperationUseCase struct {
  ExecuteStub        func(req models.AddSubOperationReq)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    req models.AddSubOperationReq
  }
}

func (fake *fakeAddSubOperationUseCase) Execute(req models.AddSubOperationReq) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    req models.AddSubOperationReq
  }{req})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    fake.ExecuteStub(req)
  }

  return
}

func (fake *fakeAddSubOperationUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeAddSubOperationUseCase) ExecuteArgsForCall(i int) models.AddSubOperationReq {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].req
}
