// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeAddSubOpUseCase struct {
  ExecuteStub        func(req models.AddSubOpReq)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    req models.AddSubOpReq
  }
}

func (fake *fakeAddSubOpUseCase) Execute(req models.AddSubOpReq) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    req models.AddSubOpReq
  }{req})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    fake.ExecuteStub(req)
  }

  return
}

func (fake *fakeAddSubOpUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeAddSubOpUseCase) ExecuteArgsForCall(i int) models.AddSubOpReq {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].req
}
