// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeListPipelinesUcExecuter struct {
  ExecuteStub        func() (pipelines []models.PipelineView, err error)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct{}
  executeReturns     struct {
                       result1 []models.PipelineView
                       result2 error
                     }
}

func (fake *fakeListPipelinesUcExecuter) Execute() (pipelines []models.PipelineView, err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct{}{})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    return fake.ExecuteStub()
  } else {
    return fake.executeReturns.result1, fake.executeReturns.result2
  }
}

func (fake *fakeListPipelinesUcExecuter) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeListPipelinesUcExecuter) ExecuteReturns(result1 []models.PipelineView, result2 error) {
  fake.ExecuteStub = nil
  fake.executeReturns = struct {
    result1 []models.PipelineView
    result2 error
  }{result1, result2}
}
