// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeAddOpUseCase struct {
  ExecuteStub        func(req models.AddOpReq)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    req models.AddOpReq
  }
}

func (fake *fakeAddOpUseCase) Execute(req models.AddOpReq) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    req models.AddOpReq
  }{req})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    fake.ExecuteStub(req)
  }

  return
}

func (fake *fakeAddOpUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeAddOpUseCase) ExecuteArgsForCall(i int) models.AddOpReq {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].req
}
