// This file was generated by counterfeiter
package core

import (
  "sync"
)

type fakeCompositionRoot struct {
  RunOpUseCaseStub                 func() runOpUseCase
  runOpUseCaseMutex                sync.RWMutex
  runOpUseCaseArgsForCall          []struct{}
  runOpUseCaseReturns              struct {
                                     result1 runOpUseCase
                                   }
  AddSubOpUseCaseStub              func() addSubOpUseCase
  addSubOpUseCaseMutex             sync.RWMutex
  addSubOpUseCaseArgsForCall       []struct{}
  addSubOpUseCaseReturns           struct {
                                     result1 addSubOpUseCase
                                   }
  GetEventStreamUseCaseStub        func() getEventStreamUseCase
  getEventStreamUseCaseMutex       sync.RWMutex
  getEventStreamUseCaseArgsForCall []struct{}
  getEventStreamUseCaseReturns     struct {
                                     result1 getEventStreamUseCase
                                   }
  KillOpRunUseCaseStub             func() killOpRunUseCase
  killOpRunUseCaseMutex            sync.RWMutex
  killOpRunUseCaseArgsForCall      []struct{}
  killOpRunUseCaseReturns          struct {
                                     result1 killOpRunUseCase
                                   }
}

func (fake *fakeCompositionRoot) RunOpUseCase() runOpUseCase {
  fake.runOpUseCaseMutex.Lock()
  fake.runOpUseCaseArgsForCall = append(fake.runOpUseCaseArgsForCall, struct{}{})
  fake.runOpUseCaseMutex.Unlock()
  if fake.RunOpUseCaseStub != nil {
    return fake.RunOpUseCaseStub()
  } else {
    return fake.runOpUseCaseReturns.result1
  }
}

func (fake *fakeCompositionRoot) RunOpUseCaseCallCount() int {
  fake.runOpUseCaseMutex.RLock()
  defer fake.runOpUseCaseMutex.RUnlock()
  return len(fake.runOpUseCaseArgsForCall)
}

func (fake *fakeCompositionRoot) RunOpUseCaseReturns(result1 runOpUseCase) {
  fake.RunOpUseCaseStub = nil
  fake.runOpUseCaseReturns = struct {
    result1 runOpUseCase
  }{result1}
}

func (fake *fakeCompositionRoot) AddSubOpUseCase() addSubOpUseCase {
  fake.addSubOpUseCaseMutex.Lock()
  fake.addSubOpUseCaseArgsForCall = append(fake.addSubOpUseCaseArgsForCall, struct{}{})
  fake.addSubOpUseCaseMutex.Unlock()
  if fake.AddSubOpUseCaseStub != nil {
    return fake.AddSubOpUseCaseStub()
  } else {
    return fake.addSubOpUseCaseReturns.result1
  }
}

func (fake *fakeCompositionRoot) AddSubOpUseCaseCallCount() int {
  fake.addSubOpUseCaseMutex.RLock()
  defer fake.addSubOpUseCaseMutex.RUnlock()
  return len(fake.addSubOpUseCaseArgsForCall)
}

func (fake *fakeCompositionRoot) AddSubOpUseCaseReturns(result1 addSubOpUseCase) {
  fake.AddSubOpUseCaseStub = nil
  fake.addSubOpUseCaseReturns = struct {
    result1 addSubOpUseCase
  }{result1}
}

func (fake *fakeCompositionRoot) GetEventStreamUseCase() getEventStreamUseCase {
  fake.getEventStreamUseCaseMutex.Lock()
  fake.getEventStreamUseCaseArgsForCall = append(fake.getEventStreamUseCaseArgsForCall, struct{}{})
  fake.getEventStreamUseCaseMutex.Unlock()
  if fake.GetEventStreamUseCaseStub != nil {
    return fake.GetEventStreamUseCaseStub()
  } else {
    return fake.getEventStreamUseCaseReturns.result1
  }
}

func (fake *fakeCompositionRoot) GetEventStreamUseCaseCallCount() int {
  fake.getEventStreamUseCaseMutex.RLock()
  defer fake.getEventStreamUseCaseMutex.RUnlock()
  return len(fake.getEventStreamUseCaseArgsForCall)
}

func (fake *fakeCompositionRoot) GetEventStreamUseCaseReturns(result1 getEventStreamUseCase) {
  fake.GetEventStreamUseCaseStub = nil
  fake.getEventStreamUseCaseReturns = struct {
    result1 getEventStreamUseCase
  }{result1}
}

func (fake *fakeCompositionRoot) KillOpRunUseCase() killOpRunUseCase {
  fake.killOpRunUseCaseMutex.Lock()
  fake.killOpRunUseCaseArgsForCall = append(fake.killOpRunUseCaseArgsForCall, struct{}{})
  fake.killOpRunUseCaseMutex.Unlock()
  if fake.KillOpRunUseCaseStub != nil {
    return fake.KillOpRunUseCaseStub()
  } else {
    return fake.killOpRunUseCaseReturns.result1
  }
}

func (fake *fakeCompositionRoot) KillOpRunUseCaseCallCount() int {
  fake.killOpRunUseCaseMutex.RLock()
  defer fake.killOpRunUseCaseMutex.RUnlock()
  return len(fake.killOpRunUseCaseArgsForCall)
}

func (fake *fakeCompositionRoot) KillOpRunUseCaseReturns(result1 killOpRunUseCase) {
  fake.KillOpRunUseCaseStub = nil
  fake.killOpRunUseCaseReturns = struct {
    result1 killOpRunUseCase
  }{result1}
}
