// This file was generated by counterfeiter
package core

import (
  "sync"
  "github.com/dev-op-spec/engine/core/models"
)

type fakeAddOperationUseCase struct {
  ExecuteStub        func(req models.AddOperationReq)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct {
    req models.AddOperationReq
  }
}

func (fake *fakeAddOperationUseCase) Execute(req models.AddOperationReq) (err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
    req models.AddOperationReq
  }{req})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    fake.ExecuteStub(req)
  }

  return
}

func (fake *fakeAddOperationUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *fakeAddOperationUseCase) ExecuteArgsForCall(i int) models.AddOperationReq {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return fake.executeArgsForCall[i].req
}
