// Code generated by counterfeiter. DO NOT EDIT.
package interpolater

import (
	"sync"
)

type fakeObjectInterpolater struct {
	InterpolateStub        func(s string, varName string, varValue map[string]interface{}) string
	interpolateMutex       sync.RWMutex
	interpolateArgsForCall []struct {
		s        string
		varName  string
		varValue map[string]interface{}
	}
	interpolateReturns struct {
		result1 string
	}
	interpolateReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeObjectInterpolater) Interpolate(s string, varName string, varValue map[string]interface{}) string {
	fake.interpolateMutex.Lock()
	ret, specificReturn := fake.interpolateReturnsOnCall[len(fake.interpolateArgsForCall)]
	fake.interpolateArgsForCall = append(fake.interpolateArgsForCall, struct {
		s        string
		varName  string
		varValue map[string]interface{}
	}{s, varName, varValue})
	fake.recordInvocation("Interpolate", []interface{}{s, varName, varValue})
	fake.interpolateMutex.Unlock()
	if fake.InterpolateStub != nil {
		return fake.InterpolateStub(s, varName, varValue)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.interpolateReturns.result1
}

func (fake *fakeObjectInterpolater) InterpolateCallCount() int {
	fake.interpolateMutex.RLock()
	defer fake.interpolateMutex.RUnlock()
	return len(fake.interpolateArgsForCall)
}

func (fake *fakeObjectInterpolater) InterpolateArgsForCall(i int) (string, string, map[string]interface{}) {
	fake.interpolateMutex.RLock()
	defer fake.interpolateMutex.RUnlock()
	return fake.interpolateArgsForCall[i].s, fake.interpolateArgsForCall[i].varName, fake.interpolateArgsForCall[i].varValue
}

func (fake *fakeObjectInterpolater) InterpolateReturns(result1 string) {
	fake.InterpolateStub = nil
	fake.interpolateReturns = struct {
		result1 string
	}{result1}
}

func (fake *fakeObjectInterpolater) InterpolateReturnsOnCall(i int, result1 string) {
	fake.InterpolateStub = nil
	if fake.interpolateReturnsOnCall == nil {
		fake.interpolateReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.interpolateReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *fakeObjectInterpolater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.interpolateMutex.RLock()
	defer fake.interpolateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *fakeObjectInterpolater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
