// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"
)

type FakeEnsureNetworkExistser struct {
	EnsureNetworkExistsStub        func(context.Context, string) error
	ensureNetworkExistsMutex       sync.RWMutex
	ensureNetworkExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	ensureNetworkExistsReturns struct {
		result1 error
	}
	ensureNetworkExistsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExists(arg1 context.Context, arg2 string) error {
	fake.ensureNetworkExistsMutex.Lock()
	ret, specificReturn := fake.ensureNetworkExistsReturnsOnCall[len(fake.ensureNetworkExistsArgsForCall)]
	fake.ensureNetworkExistsArgsForCall = append(fake.ensureNetworkExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("EnsureNetworkExists", []interface{}{arg1, arg2})
	fake.ensureNetworkExistsMutex.Unlock()
	if fake.EnsureNetworkExistsStub != nil {
		return fake.EnsureNetworkExistsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.ensureNetworkExistsReturns
	return fakeReturns.result1
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExistsCallCount() int {
	fake.ensureNetworkExistsMutex.RLock()
	defer fake.ensureNetworkExistsMutex.RUnlock()
	return len(fake.ensureNetworkExistsArgsForCall)
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExistsCalls(stub func(context.Context, string) error) {
	fake.ensureNetworkExistsMutex.Lock()
	defer fake.ensureNetworkExistsMutex.Unlock()
	fake.EnsureNetworkExistsStub = stub
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExistsArgsForCall(i int) (context.Context, string) {
	fake.ensureNetworkExistsMutex.RLock()
	defer fake.ensureNetworkExistsMutex.RUnlock()
	argsForCall := fake.ensureNetworkExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExistsReturns(result1 error) {
	fake.ensureNetworkExistsMutex.Lock()
	defer fake.ensureNetworkExistsMutex.Unlock()
	fake.EnsureNetworkExistsStub = nil
	fake.ensureNetworkExistsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEnsureNetworkExistser) EnsureNetworkExistsReturnsOnCall(i int, result1 error) {
	fake.ensureNetworkExistsMutex.Lock()
	defer fake.ensureNetworkExistsMutex.Unlock()
	fake.EnsureNetworkExistsStub = nil
	if fake.ensureNetworkExistsReturnsOnCall == nil {
		fake.ensureNetworkExistsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureNetworkExistsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeEnsureNetworkExistser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.ensureNetworkExistsMutex.RLock()
	defer fake.ensureNetworkExistsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEnsureNetworkExistser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
