// Code generated by counterfeiter. DO NOT EDIT.
package value

import (
	"sync"

	"github.com/opctl/sdk-golang/model"
)

type FakeConstructor struct {
	ConstructStub        func(data interface{}) (*model.Value, error)
	constructMutex       sync.RWMutex
	constructArgsForCall []struct {
		data interface{}
	}
	constructReturns struct {
		result1 *model.Value
		result2 error
	}
	constructReturnsOnCall map[int]struct {
		result1 *model.Value
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConstructor) Construct(data interface{}) (*model.Value, error) {
	fake.constructMutex.Lock()
	ret, specificReturn := fake.constructReturnsOnCall[len(fake.constructArgsForCall)]
	fake.constructArgsForCall = append(fake.constructArgsForCall, struct {
		data interface{}
	}{data})
	fake.recordInvocation("Construct", []interface{}{data})
	fake.constructMutex.Unlock()
	if fake.ConstructStub != nil {
		return fake.ConstructStub(data)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.constructReturns.result1, fake.constructReturns.result2
}

func (fake *FakeConstructor) ConstructCallCount() int {
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	return len(fake.constructArgsForCall)
}

func (fake *FakeConstructor) ConstructArgsForCall(i int) interface{} {
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	return fake.constructArgsForCall[i].data
}

func (fake *FakeConstructor) ConstructReturns(result1 *model.Value, result2 error) {
	fake.ConstructStub = nil
	fake.constructReturns = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeConstructor) ConstructReturnsOnCall(i int, result1 *model.Value, result2 error) {
	fake.ConstructStub = nil
	if fake.constructReturnsOnCall == nil {
		fake.constructReturnsOnCall = make(map[int]struct {
			result1 *model.Value
			result2 error
		})
	}
	fake.constructReturnsOnCall[i] = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeConstructor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConstructor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ Constructor = new(FakeConstructor)
