// Code generated by counterfeiter. DO NOT EDIT.
package data

import (
	"context"
	"sync"

	"github.com/opctl/sdk-golang/model"
)

type FakeProvider struct {
	TryResolveStub        func(ctx context.Context, dataRef string) (model.DataHandle, error)
	tryResolveMutex       sync.RWMutex
	tryResolveArgsForCall []struct {
		ctx     context.Context
		dataRef string
	}
	tryResolveReturns struct {
		result1 model.DataHandle
		result2 error
	}
	tryResolveReturnsOnCall map[int]struct {
		result1 model.DataHandle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) TryResolve(ctx context.Context, dataRef string) (model.DataHandle, error) {
	fake.tryResolveMutex.Lock()
	ret, specificReturn := fake.tryResolveReturnsOnCall[len(fake.tryResolveArgsForCall)]
	fake.tryResolveArgsForCall = append(fake.tryResolveArgsForCall, struct {
		ctx     context.Context
		dataRef string
	}{ctx, dataRef})
	fake.recordInvocation("TryResolve", []interface{}{ctx, dataRef})
	fake.tryResolveMutex.Unlock()
	if fake.TryResolveStub != nil {
		return fake.TryResolveStub(ctx, dataRef)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.tryResolveReturns.result1, fake.tryResolveReturns.result2
}

func (fake *FakeProvider) TryResolveCallCount() int {
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	return len(fake.tryResolveArgsForCall)
}

func (fake *FakeProvider) TryResolveArgsForCall(i int) (context.Context, string) {
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	return fake.tryResolveArgsForCall[i].ctx, fake.tryResolveArgsForCall[i].dataRef
}

func (fake *FakeProvider) TryResolveReturns(result1 model.DataHandle, result2 error) {
	fake.TryResolveStub = nil
	fake.tryResolveReturns = struct {
		result1 model.DataHandle
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) TryResolveReturnsOnCall(i int, result1 model.DataHandle, result2 error) {
	fake.TryResolveStub = nil
	if fake.tryResolveReturnsOnCall == nil {
		fake.tryResolveReturnsOnCall = make(map[int]struct {
			result1 model.DataHandle
			result2 error
		})
	}
	fake.tryResolveReturnsOnCall[i] = struct {
		result1 model.DataHandle
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ Provider = new(FakeProvider)
