// Code generated by counterfeiter. DO NOT EDIT.
package pkgs

import (
	"net/http"
	"sync"
)

type FakeHandler struct {
	HandleStub        func(httpResp http.ResponseWriter, httpReq *http.Request)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		httpResp http.ResponseWriter
		httpReq  *http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHandler) Handle(httpResp http.ResponseWriter, httpReq *http.Request) {
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		httpResp http.ResponseWriter
		httpReq  *http.Request
	}{httpResp, httpReq})
	fake.recordInvocation("Handle", []interface{}{httpResp, httpReq})
	fake.handleMutex.Unlock()
	if fake.HandleStub != nil {
		fake.HandleStub(httpResp, httpReq)
	}
}

func (fake *FakeHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeHandler) HandleArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return fake.handleArgsForCall[i].httpResp, fake.handleArgsForCall[i].httpReq
}

func (fake *FakeHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ Handler = new(FakeHandler)
