// This file was generated by counterfeiter
package os

import "sync"

type fakeListNamesOfChildDirsUseCase struct {
	ExecuteStub        func(pathToPERATIONarentDir string) (namesOfChildDirs []string, err error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		pathToPERATIONarentDir string
	}
	executeReturns struct {
		result1 []string
		result2 error
	}
}

func (fake *fakeListNamesOfChildDirsUseCase) Execute(pathToPERATIONarentDir string) (namesOfChildDirs []string, err error) {
	fake.executeMutex.Lock()
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		pathToPERATIONarentDir string
	}{pathToPERATIONarentDir})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(pathToPERATIONarentDir)
	} else {
		return fake.executeReturns.result1, fake.executeReturns.result2
	}
}

func (fake *fakeListNamesOfChildDirsUseCase) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *fakeListNamesOfChildDirsUseCase) ExecuteArgsForCall(i int) string {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].pathToPERATIONarentDir
}

func (fake *fakeListNamesOfChildDirsUseCase) ExecuteReturns(result1 []string, result2 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}
