// This file was generated by counterfeiter
package os

import "sync"

type FakeListNamesOfDevOpDirsUseCase struct {
  ExecuteStub        func() (namesOfDevOpDirs []string, err error)
  executeMutex       sync.RWMutex
  executeArgsForCall []struct{}
  executeReturns     struct {
                       result1 []string
                       result2 error
                     }
}

func (fake *FakeListNamesOfDevOpDirsUseCase) Execute() (namesOfDevOpDirs []string, err error) {
  fake.executeMutex.Lock()
  fake.executeArgsForCall = append(fake.executeArgsForCall, struct{}{})
  fake.executeMutex.Unlock()
  if fake.ExecuteStub != nil {
    return fake.ExecuteStub()
  } else {
    return fake.executeReturns.result1, fake.executeReturns.result2
  }
}

func (fake *FakeListNamesOfDevOpDirsUseCase) ExecuteCallCount() int {
  fake.executeMutex.RLock()
  defer fake.executeMutex.RUnlock()
  return len(fake.executeArgsForCall)
}

func (fake *FakeListNamesOfDevOpDirsUseCase) ExecuteReturns(result1 []string, result2 error) {
  fake.ExecuteStub = nil
  fake.executeReturns = struct {
    result1 []string
    result2 error
  }{result1, result2}
}
