// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/opctl/opctl/sdks/go/model"
)

type FakeCoerceToArrayOrObjecter struct {
	CoerceToArrayOrObjectStub        func(*model.Value) (*model.Value, error)
	coerceToArrayOrObjectMutex       sync.RWMutex
	coerceToArrayOrObjectArgsForCall []struct {
		arg1 *model.Value
	}
	coerceToArrayOrObjectReturns struct {
		result1 *model.Value
		result2 error
	}
	coerceToArrayOrObjectReturnsOnCall map[int]struct {
		result1 *model.Value
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObject(arg1 *model.Value) (*model.Value, error) {
	fake.coerceToArrayOrObjectMutex.Lock()
	ret, specificReturn := fake.coerceToArrayOrObjectReturnsOnCall[len(fake.coerceToArrayOrObjectArgsForCall)]
	fake.coerceToArrayOrObjectArgsForCall = append(fake.coerceToArrayOrObjectArgsForCall, struct {
		arg1 *model.Value
	}{arg1})
	fake.recordInvocation("CoerceToArrayOrObject", []interface{}{arg1})
	fake.coerceToArrayOrObjectMutex.Unlock()
	if fake.CoerceToArrayOrObjectStub != nil {
		return fake.CoerceToArrayOrObjectStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.coerceToArrayOrObjectReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObjectCallCount() int {
	fake.coerceToArrayOrObjectMutex.RLock()
	defer fake.coerceToArrayOrObjectMutex.RUnlock()
	return len(fake.coerceToArrayOrObjectArgsForCall)
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObjectCalls(stub func(*model.Value) (*model.Value, error)) {
	fake.coerceToArrayOrObjectMutex.Lock()
	defer fake.coerceToArrayOrObjectMutex.Unlock()
	fake.CoerceToArrayOrObjectStub = stub
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObjectArgsForCall(i int) *model.Value {
	fake.coerceToArrayOrObjectMutex.RLock()
	defer fake.coerceToArrayOrObjectMutex.RUnlock()
	argsForCall := fake.coerceToArrayOrObjectArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObjectReturns(result1 *model.Value, result2 error) {
	fake.coerceToArrayOrObjectMutex.Lock()
	defer fake.coerceToArrayOrObjectMutex.Unlock()
	fake.CoerceToArrayOrObjectStub = nil
	fake.coerceToArrayOrObjectReturns = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCoerceToArrayOrObjecter) CoerceToArrayOrObjectReturnsOnCall(i int, result1 *model.Value, result2 error) {
	fake.coerceToArrayOrObjectMutex.Lock()
	defer fake.coerceToArrayOrObjectMutex.Unlock()
	fake.CoerceToArrayOrObjectStub = nil
	if fake.coerceToArrayOrObjectReturnsOnCall == nil {
		fake.coerceToArrayOrObjectReturnsOnCall = make(map[int]struct {
			result1 *model.Value
			result2 error
		})
	}
	fake.coerceToArrayOrObjectReturnsOnCall[i] = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCoerceToArrayOrObjecter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.coerceToArrayOrObjectMutex.RLock()
	defer fake.coerceToArrayOrObjectMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCoerceToArrayOrObjecter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
