// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/opctl/opctl/sdks/go/model"
	"github.com/opctl/opctl/sdks/go/opspec/interpreter/reference/identifier/value"
)

type FakeConstructor struct {
	ConstructStub        func(interface{}) (*model.Value, error)
	constructMutex       sync.RWMutex
	constructArgsForCall []struct {
		arg1 interface{}
	}
	constructReturns struct {
		result1 *model.Value
		result2 error
	}
	constructReturnsOnCall map[int]struct {
		result1 *model.Value
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConstructor) Construct(arg1 interface{}) (*model.Value, error) {
	fake.constructMutex.Lock()
	ret, specificReturn := fake.constructReturnsOnCall[len(fake.constructArgsForCall)]
	fake.constructArgsForCall = append(fake.constructArgsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("Construct", []interface{}{arg1})
	fake.constructMutex.Unlock()
	if fake.ConstructStub != nil {
		return fake.ConstructStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.constructReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConstructor) ConstructCallCount() int {
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	return len(fake.constructArgsForCall)
}

func (fake *FakeConstructor) ConstructCalls(stub func(interface{}) (*model.Value, error)) {
	fake.constructMutex.Lock()
	defer fake.constructMutex.Unlock()
	fake.ConstructStub = stub
}

func (fake *FakeConstructor) ConstructArgsForCall(i int) interface{} {
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	argsForCall := fake.constructArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConstructor) ConstructReturns(result1 *model.Value, result2 error) {
	fake.constructMutex.Lock()
	defer fake.constructMutex.Unlock()
	fake.ConstructStub = nil
	fake.constructReturns = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeConstructor) ConstructReturnsOnCall(i int, result1 *model.Value, result2 error) {
	fake.constructMutex.Lock()
	defer fake.constructMutex.Unlock()
	fake.ConstructStub = nil
	if fake.constructReturnsOnCall == nil {
		fake.constructReturnsOnCall = make(map[int]struct {
			result1 *model.Value
			result2 error
		})
	}
	fake.constructReturnsOnCall[i] = struct {
		result1 *model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeConstructor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.constructMutex.RLock()
	defer fake.constructMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConstructor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ value.Constructor = new(FakeConstructor)
