name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Opctl
      run: curl -L https://github.com/opctl/opctl/releases/latest/download/opctl-linux-amd64.tgz | sudo tar -xzv -C /usr/local/bin
    - name: Create Release for latest version
      id: create_release
      run: |
        opctl run -a github='{"username":"${{ github.actor }}", "accessToken": "${{ github.token }}"}' release/to-github
      
